### ISSUE TITLE
Allow images of fixed size to be uploaded as part of a provenance record.

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#10]
I don't know what a normal size here is. I don't think it has to be very high resolution. We could have a security problem with people filling up space by adding data as a denial of service attack.

A good picture of a single printed page or a medium-resolution color picture of a device should be sufficient.

**Comment by RobertLRead** [comment]
Yes! But I don't know what is reasonable.  People seem to use 10 MB today. I have no idea how encryption of photos works---I guess you program a blob-store somewhat and use some very light encryption on the big blob, and put the key to that encryption inside the strongly encrypted provenance record?

**Comment by devhawk** [comment]
In the current design of the dev branch, `ProvenanceRecordModel` stores both mime type and the encrypted data blob. I have a simple test working where I upload an existing image via an HTML form. image and text get encrypted the same way - we get the info as a blob then use an AES 256 cypher to encrypt it.

**Comment by devhawk** [comment]
Deployed demo has separate tables for provenance records (JSON encoding) and attachments (theoretically any binary format but expected to be images). 

As per above comment, BLOB storage such as AWS S3 would likely be cheaper in the long run for storing encrypted images. Note, our storage table for attachments needs to have a mechanism for storing MIME type of the unencrypted attachment and encryption init vector (aka salt) as metadata with the encrypted attachment.
