### ISSUE TITLE
If the provenance url does not define a proper url, it does not give a good warning....

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#108]
If you take a URL like:

http://localhost:3000/provenance/%7B%7Bchildkey%7D%7D

Which does NOT specify a proper device key, it should be obvious that you have not specified a device key. At present it fails nearly silently.

**Comment by RobertLRead** [comment]
@chihlinc I'm assigning this to you as a relatively easy bug (but it does require knowing Nuxt). If you don't think you can get to it by April 15th, please assign it to @judithweng .

**Comment by chihlinc** [comment]
Should we use an error message to display on the webpage, a pop-up notification, or some other form of visual or textual feedback?

**Comment by RobertLRead** [comment]
Dear Coco (@chihlinc), If you had put @RobertLRead in your comment, I would have been notified of this question.

I recommend that we display in the webpage the content that the device key is not found. This may require you to learn how to do conditional rendering with Vue/Nuxt (there are other examples of this in the code.)

**Comment by chihlinc** [comment]
@RobertLRead I modified the code and pushed it in the coco-fix code branch. Please review the codes.
