### ISSUE TITLE
[BUG] Code does not allow establishing a container relationship after the creation of the group

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#115]
The legacy container system written by @judithweng had a means of specifying a parent-child relationship apart from the creation of a group (which does that all at one time). This has not yet been ported to the new code.

It is an essential feature, since someone may want to create this relationship after they have already created the child keys. When I originally designed the container system, I think I specified a way to do it, but I think Judith did something slightly different.

**Comment by RobertLRead** [comment]
We need to enforce the idea that a child can have only one parent (or an item can be contained in only one container.)  We have to be careful not to allow the establishment of a parent/containment relationship which grants authority to a device key which it should not have.

**Comment by RobertLRead** [comment]
@judithweng I am assigning this to you; this is the largest feature which I didn't get done in porting your code over.

**Comment by judithweng** [comment]
This issue has been fixed and merged into the main branch.
