### ISSUE TITLE
[FEATURE REQUEST] Automatically convert URLs in prov records to clickable anchor tags

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#117]

**Comment by RobertLRead** [comment]
@noramoor2007 I think this is a relatively low priority bug, but you might want to do it after you get the word filter working. It is similar in nature, in that it can be a piece of pure javascript that runs in the browser (not the backend). This could be the first issue where you are actually directly coding in the frontend.

**Comment by RobertLRead** [comment]
Note: This issue concerns only making a URL clickable, not anything more complicated. This is usually done with "anchor" tags --- by convention a clickable link is often rendered as an underlined blue text.
