### ISSUE TITLE
Generate an image which is the "GOSQAS" seal

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#13]
Although the QR code and/or the deviceid is the most important part of it, we would prefer that devices tracked via GOSQAS be labelled with a GOSQAS seal/image which brands it (or "unbrands") it by mentioning the GOSQAS system and giving the URL ot the GOSQAS main website. This image will have to be desigend before a progammer can generate it. The general idea is a combintation of text and a QR code and possibly a GOSQAS logo.

devhawk comment - as long as I'm not expected to design the logo, this should be straightforward

**Comment by devhawk** [comment]
We may need to use a different QR code library. https://github.com/soldair/node-qrcode doesn't appear to support generation of QR codes w/ a logo in them

**Comment by RobertLRead** [comment]
I was rather assuming that we would compose an image differently, with the QR code ON the seal, but not being the seal itself. This was my initial interpretation:
![GOSQAS Seal (2)](https://github.com/gosqas/gosqas-demo1/assets/5296671/bbdbb689-7249-4627-9caf-2d88d9db2a57)

However, I am NOT an artist and also don't know how big the QR code has to be relative to other stuff.

**Comment by devhawk** [comment]
Cool, this is even easier then.

**Comment by devhawk** [comment]
FYI, the /device/:deviceKey page already generates the QR code like we would see in this image. I can update that page to look more like this image. 

@RobertLRead do you have a higher resolution version of the GOSQAS seal?

**Comment by RobertLRead** [comment]
A Higher Res image has been provided in issue [#15](https://github.com/gosqas/asset-provenance-tracking/issues/15).

Note: the bottom part of the designed GOSQAS Seal ( the "top 3 certifications") should not be included; that is a low-priority enhancement for later versions.  However, adding a "Product Description" is a good idea. I will write a new story for that.

**Comment by devhawk** [comment]
dupe #19
