### ISSUE TITLE
[FEATURE REQUEST] Finalize logo & brand colors

### ISSUE THREAD

**Issue by ninalahoti** [gosqasorg/asset-provenance-tracking#131]
**Is your feature request related to a problem? Please describe.**
Need to finalize these things before moving forward with designing other elements ex. website & sticker

**Describe the solution you'd like**
Finalize and agree upon logo and colors

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by RobertLRead** [comment]
@ninalahoti can this be closed?
