### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#135]
This is a rather unpleasant issue. I think we should a list of 100-1000 English words that are not medical terms, but which are either considered obscene or are used to refer to illicit activities or drugs. For example, we should forbid the work "shit" from our list, although we must allow the word "feces", because the words "feces" and "fecal" have important medical uses.

I see no reason these should not be embedded in the code, though we could in theory put them in a separate file; but if we do that, we make it harder for an outside to suggest new forbidden words, such as in Language other than English. For example, I think the word "culo" in Spanish has no medical use; but we cannot hope to head off all obscene words in all languages. By making an open system, we allow other cultures to potentially assist us.

There are other words which we should forbid which are not directly obscene, but have no value in this produce, like "busty". 

There are racial terms that we should exclude.

I do not believe we can forbid a word like "gun" as there may be medical uses of that word.

**Comment by RobertLRead** [comment]
@MairinOGrady I have assigned this to you because it is something a writer could do---it is just the research of a list of words. However, it is a potentially unpleasant and offensive task, if you are squeamish about reading dirty words. I am not, so you can assign this back to me if you would rather not take this on. Or if you want to do some topics but not others, that is understandable.

**Comment by MairinOGrady** [comment]
Hi Robert,

I can start putting together a list. Would this go directly into GitHub or as a Word Document first?

**Comment by RobertLRead** [comment]
@MairinOGrady did a good job with this. I modified her list slightly. I consider it very incomplete, but a first step. 

[Words to Cut Out of Code.v2.docx.zip](https://github.com/gosqasorg/asset-provenance-tracking/files/15266280/Words.to.Cut.Out.of.Code.v2.docx.zip)

**Comment by judithweng** [comment]
Closing this issue as it was solved through PR #218
