### ISSUE TITLE
Compare new system to old system in terms of GUI quality

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#139]

**Comment by noramoor2007** [comment]
[Issue #139 - Comparing Old to New System.pdf](https://github.com/gosqasorg/asset-provenance-tracking/files/15299952/Issue.139.-.Comparing.Old.to.New.System.pdf)

**Comment by RobertLRead** [comment]
This is good work, but it is hard to use because you used a PDF. Can you place the text in the comments in the issue itself? This will make it easier for me to break it up into issues to assign to others.

**Comment by RobertLRead** [comment]
@noramoor2007  proposes:

> Since users no longer have access to the list of sample devices, it's challenging to view
> the devices that have already been created. I propose offering users the option to create
> containers and devices in either a public or a private domain. The public domain would
> cater to less sensitive information, like tracking the amount of trash collected, while the
> private domain would accommodate more confidential and higher-priority devices. For
> instance, those used for communication in critical contexts like in Ukraine.

I don't want to implement this because it is going backward, in a sense, and making our system more complicated. However, if we created read-only devices, which were locked for new additions to the history (similar to the "expiration" concept I made earlier), then we could list a set of sample devices through pure documentation---with no code changes. I will ask Victoria about this.

**Comment by RobertLRead** [comment]
@noramoor2007  proposes creating an informative "hover" text. However, to my knowledge "hover" does not work well on phones. @ninalahoti is there a mobile-friendly alternative? Is there something we can do here to allow the reader to get a defintion of the words we use in the GUI like "device"?

**Comment by RobertLRead** [comment]
@noramoor2007 proposes that we change the button wording from "Submit" to something more specific like "Create Container Group". She further proposes uses white text on a colored background, but I am going to take no action on that, since that will be part of the style guide as per @ninalahoti. But I will create an issue to improve the text---"Submit" is not a good button action label.
