### ISSUE TITLE
Here is a logo that can be used for GOSQAS

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#15]
![Sign-purple-1](https://github.com/gosqas/asset-provenance-tracking/assets/5296671/daaac349-4078-46e3-9022-5bc8234a72e8)

Christina, do you want to pick a font and/or put this in "word art" as you did before? Maybe the "O" in GOSQAS?

**Comment by christinacole** [comment]
Yes! I’ll play around with this over the weekend and send a few options to choose from.-Christina On Jun 16, 2023, at 12:38 PM, Robert L. Read ***@***.***> wrote:﻿

Christina, do you want to pick a font and/or put this in "word art" as you did before? Maybe the "O" in GOSQAS?
