### ISSUE TITLE
[BUG] Make sure ALL our code files have the AGPL license copyright preable...

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#160]
This is a non-coding code change. 

I want us to follow the best practice of adding the Aferro GPL copyright notice to all of our code files (in a comment at the top.) The way you add a comment depends on the kind of file (.html, .vue, .js, .ts, etc., but it is very strateforward.

This is a good "first issue", so I am assigning it to @anushashringi042 .  @noramoor2007 may want to give here guidance.

It is possible that neither of you know precisely how to do this; please ask @devhawk (since I am soon on vaction), or me if Harry is not around.

**Comment by noramoor2007** [comment]
We are having technical difficulties trying to get Anusha's terminal working, so that she can commit and push her changes to a branch.

**Comment by anushashringi042** [comment]
Done. Can you view my linked pull request?
