### ISSUE TITLE
Add "About" and "Contact" pages

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#168]
We need the content for this page and to decide whether to make this scroll on the main page, or have it be a separate page.

**Comment by ninalahoti** [comment]
Divided into three pages:
https://github.com/gosqasorg/asset-provenance-tracking/issues/201
https://github.com/gosqasorg/asset-provenance-tracking/issues/202
https://github.com/gosqasorg/asset-provenance-tracking/issues/203

**Comment by vjaqua** [comment]
The style guide should be followed https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=0-1&t=NQFju1lKFeFTRE9F-0
