### ISSUE TITLE
[BUG] Delegate: Fix homepage to be closer to Figma design

### ISSUE THREAD

**Issue by ninalahoti** [gosqasorg/asset-provenance-tracking#171]
Correct color on 
- top nav
- logo text
- “Create New Device”
- “Device Image (optional)
- “Choose File” text and button
- background on “Create New Device” card
- input field filler text
Remove border on input fields
Correct toggle button appearance
Correct font sizes & line heights (applies to almost all text)
Add "Add tags (optional)" field
Add "Notify all children?" checkbox
Fix numerous spacing issues throughout
Figma link: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=7-19975&t=4N9HqwBsXNqV7SwO-1

**Comment by K42IE** [comment]
Created Sub-issues:
 https://github.com/gosqasorg/asset-provenance-tracking/issues/181
https://github.com/gosqasorg/asset-provenance-tracking/issues/180
https://github.com/gosqasorg/asset-provenance-tracking/issues/179

**Comment by K42IE** [comment]
This is for universal coloring: https://github.com/gosqasorg/asset-provenance-tracking/issues/182

**Comment by K42IE** [comment]
Delegation Complete. (Will close issue when tasks are done).
