### ISSUE TITLE
[BUG] Clean up style sheet

### ISSUE THREAD

**Issue by ninalahoti** [gosqasorg/asset-provenance-tracking#172]
Noticed a fair amount of "!important" in the style sheet
Can we clean it up, please? It's a fairly simple design, so I don't think this should be necessary if it's written correctly

**Comment by K42IE** [comment]
![image](https://github.com/user-attachments/assets/2ee5671c-9c2b-4e49-9aec-e2f4ce37d4f6)

**Comment by bencoombs** [comment]
I can't find any !important lines in the code. @ninalahoti do you know which file this was?

**Comment by vjaqua** [comment]
@ninalahoti could you please review this?
