### ISSUE TITLE
[BUG] Delegate: Update device page to be closer to Figma design

### ISSUE THREAD

**Issue by ninalahoti** [gosqasorg/asset-provenance-tracking#173]
Fix color of top nav background & logo text & links
Remove gray download button
Fix button spacing
Fix font sizes, weights, and line height
Add hover states to buttons
Sharpen the corners of the qr code:
<img width="470" alt="Screenshot 2024-06-17 at 2 51 01 PM" src="https://github.com/gosqasorg/asset-provenance-tracking/assets/71244080/41efc00f-d05b-4586-94d4-8b294a08799c">

**Comment by K42IE** [comment]
Delegated this in issues: #191 , #192, and #193
