### ISSUE TITLE
Make Navigating More Accessible in the History Record (create device, etc.)

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#177]
Current, not pretty, solution:

![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/1405a2eb-4d18-4b6b-befe-22612e7b6d04)

**Comment by ninalahoti** [comment]
New nav design here: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=668-5291&t=VlgvyNh92huHZLsA-1
