### ISSUE TITLE
Tie the Heroku app to one of our the domain names that we own

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#18]
@christina.cole has purchased several domain names for us. @devhawk is currently deploying with Heroku. After he has that working, I suggest that Harry ping Christina by email to get the domain names and get it all officially setup; he can then tie our QR code generation to that URL. This will make the demo more powerful and is probably necessary for an MVP, but it is can be done at the appropriate time.

**Comment by devhawk** [comment]
This is ready to be done as soon as I have a domain name to use

**Comment by gosqas** [comment]
She is going to get it to you tomorrow, I believe.

**Comment by devhawk** [comment]
@christinacole gave me access to the DNS settings so I have configured the hosted solution to be available at https://gosqas.org. 

Note, IN addition to the DNS settings, I set up [Automated Certificate Management](https://devcenter.heroku.com/articles/automated-certificate-management) in heroku so the site is available via HTTPS
