### ISSUE TITLE
Update Create Device Toggle on homepage

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#180]
Make this a component called "LargeToggle". Pass in the two strings. Alternatively you can make a global style for the toggle named "largeToggle". 

Wanted:

![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/d2e4b028-a504-4d4b-8693-65d4ae4d7bed)

Current:
![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/4ff93008-72be-435c-ac16-3fddc821b5e3)

https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=7-19975

**Comment by chihlinc** [comment]
@K42IE coco-update-toggle is the branch. I updated it to this. 
<img width="258" alt="Screenshot 2024-06-19 at 6 55 51 PM" src="https://github.com/gosqasorg/asset-provenance-tracking/assets/123109877/b4c04eff-716b-4222-a799-62956d1d7e99">

**Comment by K42IE** [comment]
Merged and done
