### ISSUE TITLE
Update "Create New Device" and "Create New Container" Forms on Homepage

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#181]
Make these into two components. One component will be for the "New Device Form" another for the "New Container Form". 

You should make a new folder under the "components" directory named FormComponents. Put these two components here. 

In the home page "index.vue", these components should replace the preexisting code. 

Also update the forms via the Figma Designs: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=7-19975
![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/eefedb1c-10c1-44ba-84cd-8536ca5bedc7)

![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/d7331f52-4875-40f2-b125-a57965d09cc0)

Notes about needed changes: 
“Device Image (optional)
“Choose File” text and button
background on “Create New Device” card
input field filler text
Remove border on input fields
Correct toggle button appearance
Correct font sizes & line heights (applies to almost all text)
Add "Add tags (optional)" field
Add "Notify all children?" checkbox
Fix numerous spacing issues throughout

**Comment by judithweng** [comment]
@K42IE would you mind clarifying what you mean by making these into components? My assumption was that they have always been and these currently are in the components folder.
<img width="145" alt="image" src="https://github.com/gosqasorg/asset-provenance-tracking/assets/83525666/52858538-a2c6-4fc3-8fe2-4f8828135e0d">

Index.vue refers to these currently.

**Comment by K42IE** [comment]
My bad, you are correct. Can we take it out of the provenance folder and put it into a folder with a better name ("forms" etc.) because they are used outside the history record page.

**Comment by judithweng** [comment]
@K42IE  thanks for clarifying! sounds good :)
