### ISSUE TITLE
[BUG] Color tag does not work sometimes

### ISSUE THREAD

**Issue by judithweng** [gosqasorg/asset-provenance-tracking#186]
@noramoor2007 I realized that sometimes when I add tags I get the following error (see image below)
<img width="949" alt="colortagerror" src="https://github.com/gosqasorg/asset-provenance-tracking/assets/83525666/ae7952f1-4854-4e6b-ab55-bcb157d9c90b">

I added this random Lorem Ipsum sentence "Bibendum at varius vel pharetra vel turpis nunc eget" and it failed. I did some more testing and found out specifically the word "at" creates this error. I have gotten the error a few times before but I do not remember what words I have used. Would you be able to check if you get the same error and if so, what is creating this issue? Thanks!

**Comment by RobertLRead** [comment]
@judithweng this is an important bug, and I am too busy to do it---can you prioritize this?  I think @noramoor2007 is also too busy to do it---but if she gets to it first, that is fine.

**Comment by vjaqua** [comment]
@judithweng Rob thinks he has merged this, can you verify and close if it has been fixed?

**Comment by judithweng** [comment]
@vjaqua This issue has been fixed. I will close this and mark as solved.
