### ISSUE TITLE
Make Custom Button Component (Device Page)

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#191]
Create a component for the button on the device page. (we will remove the extra download button under the QR code. Ignore this).

Notice how the radius and the padding is the same for both buttons. The only thing changing the size of the button is the label. You should not have to code the size (the css will take care of it as long as you ass the appropriate padding and radius):
![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/a119986d-67e9-447b-bcd1-a130f42bfdf2)

Here is a video to tell you how to code it (not including stylings): https://www.youtube.com/watch?v=2Evw5h_1Ko8

Put this component in the component folder. (Later we will put it in a subfolder labeled Buttons (This has extra steps that I will explain later))

Here is where the device page is located (the buttons are on line 18 and 19): 
![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/97125327-4320-40b8-9986-7341ee9547cf)

Props wanted: label (like in video) and button color.

**Comment by K42IE** [comment]
This is a delegation for issue #173.

**Comment by vjaqua** [comment]
Need to understand what this button is for @anushashringi042
