### ISSUE TITLE
Download Button on Device Page

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#192]
Task One: Remove Grey Download Button :![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/25025541/049655a5-0b41-425e-88da-2061eb3c579a)

Task Two: And make sure the styled button actually downloads the QR code (it currently does not).

Task 3: Nina also wants a higher resolution QR code

**Comment by chihlinc** [comment]
Okay!

**Comment by chihlinc** [comment]
PR  #233
