### ISSUE TITLE
New Homepage Design

### ISSUE THREAD

**Issue by ninalahoti** [gosqasorg/asset-provenance-tracking#199]
Designs here: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=668-5288&t=VlgvyNh92huHZLsA-1

**Comment by K42IE** [comment]
Note: I am going to have ally create a button component.

**Comment by vjaqua** [comment]
PR #253 has buttons, ready for review
