### ISSUE TITLE
New History record design

### ISSUE THREAD

**Issue by ninalahoti** [gosqasorg/asset-provenance-tracking#204]
Design here: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=668-5291&t=VlgvyNh92huHZLsA-1

**Comment by K42IE** [comment]
Addressed in delegated issues: https://github.com/gosqasorg/asset-provenance-tracking/issues/206 and https://github.com/gosqasorg/asset-provenance-tracking/issues/205

Todo: footer
