### ISSUE TITLE
[BUG] The initial text in the input boxes should probably be grayed out...

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#209]
I'm used to the GUI principle that a text input box often holds text which shows a bit of explanatory text, which disappears when you start typing. Normally this is grayed out. In our system, it is the same dark color as the entry text. I think it should be gray.

In the image below, "Rob Test Container" has been enterred, but "Container Description" and "Device Tag" are explanatory text. But they should not look exactly the same.

![Screenshot 2024-07-16 at 6 39 30 PM](https://github.com/user-attachments/assets/8072e7e8-9c34-4d1c-baf6-a9b0fd70b26d)

**Comment by chihlinc** [comment]
# PR 219
