### ISSUE TITLE
Provenance record API

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#21]
Eventually, we will want an API for reading/writing encrypted GOSQAS provenance records. 

As part of this work, we can do more encryption/decryption on the client which will reduce load on the hosted system

**Comment by RobertLRead** [comment]
@devhawk the priority of this has been increased; Alex Barton wants it for the report he is creating.

We want an API (it can be a REST webservice, for example), that outputs Provenance records in CSV or JSON or something.
The idea would be that someone enters a URL/key, and gets all the provenance records for key.

**Comment by devhawk** [comment]
Dupe of #56
