### ISSUE TITLE
Review Terms and Conditions

### ISSUE THREAD

**Issue by christinacole** [gosqasorg/asset-provenance-tracking#237]
Please review this document. I need help with User Data section. https://docs.google.com/document/d/1k4IfM-slMRxIEDkCLhRlwZMTMQKWzVtGWo7rL-qfwuc/edit?usp=sharing

**Comment by RobertLRead** [comment]
I have reviewed this.  I can't do much more without undertaking a serious comparison with other terms and conditions. Not being a lawyer, I have scant ability to do more.

**Comment by vjaqua** [comment]
@ninalahoti this document is ready for styling in Figma.

**Comment by ninalahoti** [comment]
For legal documents, it's best to leave the styling fairly minimal as to not distract from the text. I reformatted it a bit and added our brand typeface in the Google Doc, and it's ready to go now!

**Comment by vjaqua** [comment]
So for this to be a page on the website, similar to "About Us", does dev copy/paste from the doc and apply the default styling and font color of the other pages? The T&C page will eventually be linked to the footer.

**Comment by ninalahoti** [comment]
Ah, I had thought we were the link in the footer would be to this as a PDF. I'll make the design today

**Comment by ninalahoti** [comment]
Design here: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=1217-2&t=lIi4CZhjZdu77j39-1

**Comment by vjaqua** [comment]
Christina and I reviewed the design today and it looks fantastic, thank you! @bencoombs this is ready for assignment.
