### ISSUE TITLE
Change Wording of Copyright:  Copyright (C) 2024 GOSQAS Team -> Copyright (C) 2024 GOSQAS 

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#241]
Simply take the word "Team" out of anywhere that has this copyright. It will be comments at the top of code files. 

`Copyright (C) 2024 GOSQAS Team -> Copyright (C) 2024 GOSQAS `

**Comment by vjaqua** [comment]
@bencoombs from what I remember this was addressed directly by @K42IE as she edited it live during a meeting. This issue might be closable?

**Comment by melanielaporte** [comment]
Site has been updated.
