### ISSUE TITLE
Create Footer (include copyright)

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#246]
**!!! Add this copyright to the footer:**  © 2024 Global Open Source Quality Assurance System. All rights reserved.

![image](https://github.com/user-attachments/assets/2762a504-91ad-47be-ac23-69da5ae81c93)

https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=668-5291&t=ZUa2Y0nIjZdfd70c-0

**Dev note: Create the footer in layouts/default.vue**. See the header code for reference, in this file.

**Comment by RobertLRead** [comment]
Please make the text read "The purple hand logo and the GOQAS are marks of the Global Open Source Quality Assurance System, all rights reserved. However, our software is open source software."
