### ISSUE TITLE
De-clutter Container System

### ISSUE THREAD

**Issue by K42IE** [gosqasorg/asset-provenance-tracking#252]
As a user, I do not want to be confused that the container/child system is optional. 

In the History Record, it should be hidden behind a check box or some other UX system where the user doesn't have to see the extra content unless they need to use it. It should still be an obvious, accessible option.

This issues was made based off of user feedback. 

<img width="778" alt="image" src="https://github.com/user-attachments/assets/61588bf8-e2aa-4721-9333-0143b654b824">

**Comment by bencoombs** [comment]
Is there a design for this @ninalahoti ?

**Comment by ninalahoti** [comment]
Not yet. Is this just adding the option to hide the "Download Children Keys as CSV" button? Or will anything else be hidden?

**Comment by vjaqua** [comment]
I looked at this more closely. This user ask was based on the legacy code when the container and child text entry was included in the device creation, before there was a device and container toggle.
So addressing this to the updated code...is it possible to only have "download children keys CSV" and "notify all children" as options **only** when within a container record? When they appear in a device record it could be confusing. ![Image](https://github.com/user-attachments/assets/59960ec6-84b9-4147-93af-b681470bd772)

**Comment by vjaqua** [comment]
"notify all children" and "download children keys" can be hidden from the record and side navigation bar. This is ready for assignment @bencoombs

**Comment by noramoor2007** [comment]
When you make a container, should the reporting keys have the "Notify all children" checkbox or not? I hid the "Notify all children" checkbox for when a user creates a device:
<img width="1512" alt="Screenshot 2024-10-13 at 7 05 57 PM" src="https://github.com/user-attachments/assets/8b1acd58-b76e-430c-b7ef-184f3c3e0e9d">

When you create a new container it does appear again:
<img width="1512" alt="Screenshot 2024-10-13 at 7 05 07 PM" src="https://github.com/user-attachments/assets/263b294d-1afe-462c-87a5-0810b4de535e">

However, it also appears for a container's reporting key and child keys:
<img width="1512" alt="Screenshot 2024-10-13 at 7 05 13 PM" src="https://github.com/user-attachments/assets/712b1ca8-4024-4153-a800-d68da499cd31">
