### ISSUE TITLE
Create a bit more visual separation in the provenance

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#26]
Dear @devhawk,
Can you please create a little more visual separation between provenance records? It is hard for us to tell which timestamp is associated with which record. I recommend the "green stripe" technique of alternating background color for each record, so that no extra real estate is required.

Also, can you make the area where you "Add a Provenance Record" visually separated in some way?

![Image](https://user-images.githubusercontent.com/117682709/250703000-47550d5a-c86b-40a8-9fdb-ea10e9657741.png)

**Comment by christinacole** [comment]
Hello, I have some suggestions here. See attached.

[GOSQAS_2.0.pdf](https://github.com/gosqasorg/asset-provenance-tracking/files/11980168/GOSQAS_2.0.pdf)

**Comment by devhawk** [comment]
(I updated @christinacole comment with a copy/paste from the doc for easy reference)

**Comment by devhawk** [comment]
1. Remove redundant GOSQAS - easy enough
2. number the records - also easy, except for one question - counting up or counting down? In the example shown, is the top most record number 1 or number 7?
3. title/record/input width - this might be better suited to someone w/ better front end design skills than I have

**Comment by devhawk** [comment]
FYI, I'm using #28 to track the changes suggested by @christinacole
