### ISSUE TITLE
Make 'Device Provenance Record' page match Figma

### ISSUE THREAD

**Issue by judithweng** [gosqasorg/asset-provenance-tracking#262]
Some little fixes need to be made. 

1. Put 'Asset History Records' before the device name
2. Change 'Device ID' to 'Device Key' after the device name
3. Adjust spacing throughout. The space between the 'Jump To' section seems small. Also, the space between the description and most recent record is also small.
4. Change width of each record (the gray box) to match Figma

**Comment by bencoombs** [comment]
This should only require some light HTML and CSS editing.

https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=668-5291&node-type=section
