### ISSUE TITLE
Review and implement suggested visual layout for provenance tracking

### ISSUE THREAD

**Issue by christinacole** [gosqasorg/asset-provenance-tracking#28]
https://drive.google.com/file/d/1CztIuXl1vcVikHoGE3QWTJNt3_dYHt2u/view?usp=sharing

**Comment by devhawk** [comment]
Note, this work is also tracked by #26

**Comment by devhawk** [comment]
I'm going to use this issue to track the suggestions @christinacole made and continue to use #26 to track suggestions made by @RobertLRead
