### ISSUE TITLE
[BUG] "Children keys" appear in a legacy device record where no children keys were created

### ISSUE THREAD

**Issue by vjaqua** [gosqasorg/asset-provenance-tracking#289]
**Describe the bug**
When a legacy device record is migrated, "children keys" appear at the bottom of the record even though no children keys were created in the legacy code for that record. When clicked, these children keys show as "service unavailable." Of note: the number of children keys appearing is the same as the number of provenance records within the device record.

**Expected behavior**
Children keys should not appear within a record that did not have children keys created.

https://red-stone-00f5d251e.5.azurestaticapps.net/provenance/76LWSY6bzXJ9r6YYV2eD8K
![Image](https://github.com/user-attachments/assets/928298bf-134f-4035-8daf-afc2b8d00500)

**Desktop **
 - OS: Sonoma 14.6.1
 - Browser Chrome
 - Version 129.0.6668.60

**Comment by bencoombs** [comment]
![Image](https://github.com/user-attachments/assets/41e31ac7-0528-42e4-9da8-8a817f60cd83)
