### ISSUE TITLE
[BUG] Migration: Name of first record should become deviceName in migrated data

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#292]
**Describe the bug**
In our migration, records are not coming across with the "Device Name" properly populated. Some of the records are in use by our customers and will likely look very weird to them.

**To Reproduce**
An example can be seen here: 
[https://red-stone-00f5d251e.5.azurestaticapps.net/provenance/8FFYE6suyVbCtVAWe2sP8Y](https://red-stone-00f5d251e.5.azurestaticapps.net/provenance/8FFYE6suyVbCtVAWe2sP8Y)

The DeviceName (between the quotes) should be: 

"Help use test our software and do science! Enter the number of basking turtles you can see. Asset Provenance Records"

From: https://gosqas.org/provenance/8FFYE6suyVbCtVAWe2sP8Y

As we discussed with @devhawk in the meeting, it is probably that by decrypting the legacy blob, it shold be easy to perform this rule:

Take the name in the chronologically first provenance record in the legacy code base, and use it as the "DeviceName" slot in the new migrated record.

**Comment by devhawk** [comment]
When we convert provenance records for a legacy device, we don't handle them in any specific order. So executing the logic as described would be significantly additional effort to add logic to sort records by date. Is it good enough to simply convert the `name` field (if it exists) in the legacy provenance record to `deviceName` (as it appears in the new system)?

Example Initial record in new system ([link](https://gosqasbe.azurewebsites.net/api/provenance/8J8vtUU2STjJsxPTs1jjJ)):
```json
  {
    "record": {
      "blobType": "deviceInitializer",
      "deviceName": "Harry Test Device",
      "description": "Test Description",
      "tags": [],
      "children_key": "",
      "hasParent": false,
      "isReportingKey": false
    },
    "attachments": [
      "cf8048a18d9432368da577e6d5f2efdef2231535aaf19800eee20e45bac24820"
    ],
    "deviceID": "0905503f949815caf76d5df494e560b728650611e9702a5cccaba80925d1a18d",
    "timestamp": 1728345479018
  }
```

Initial prov record for turtles "device" ([link](https://gosqasbe.azurewebsites.net/api/provenance/8FFYE6suyVbCtVAWe2sP8Y))
```json
  {
    "record": {
      "description": "Please don't enter your name. Just enter a single number representing the number of basking turtles you can see from right in front of this sign. We will correlate it with time and weather.",
      "name": "Help use test our software and do science! Enter the number of basking turtles you can see.",
      "tags": [
        "creation"
      ]
    },
    "attachments": [],
    "deviceID": "82c35a2776f578a7211da8d196b198f32db2afbab6c019888bf77f7fa370972e",
    "timestamp": 1705958879858
  }
```

**Comment by RobertLRead** [comment]
I approve this approach as we discussed in the meeting.

**Comment by devhawk** [comment]
fixed by #302

**Comment by devhawk** [comment]
After #302 is applied
![image](https://github.com/user-attachments/assets/48616926-26d8-4da3-a131-cb655a69642f)

**Comment by RobertLRead** [comment]
This looks good!
