### ISSUE TITLE
Amend language from "device" to record (+ a few other language changes)

### ISSUE THREAD

**Issue by ninalahoti** [gosqasorg/asset-provenance-tracking#303]
New language shown here: https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=0-1&t=nGy2FYVUfCBfbUjb-1

List of changes:
- top navigation: CTA now says `View Record`
- footer: `Technical Documents` link replaced with `Terms and Conditions`
- mobile menu: two buttons replaced with `View Record` and `Create Record`
- mobile menu: `Technical Documents` link replaced with `Terms and Conditions`
- homepage: two buttons now say `View Record` and `Create Record`
- homepage: `Open Source` section description now changed to say `Our projects are created for the public good and are available free of charge.`
- homepage: buttons removed from `Interested in learning more?` section
- Global Distributed Tracking service page: toggle now says `New Record` and `New Group`
- New Device form: now titled `Create New Record`
- New Device form: `Device Name` now says `Record Name`
- New Device form: `Device Description` now says `Record Description`
- New Device form: `Device Image` now says `Record Image`
- New Device form: `Device Tag` now says `Record Tag`
- New Device form: `Create Device` now says `Create Record`
- New Container form: now titled `Create New Group`
- New Container form: `Container Name` now says `Group Name`
- New Container form: `Container Description` now says `Group Description`
- New Container form: `Container Image` now says `Group Image`
- New Container form: `Container tag` now says `Group tag`
- New Container form: `Number of contained records (optional)` now says `Number of grouped records (optional)`
- New Container form: `Customize contained record names?` now says `Customize grouped record names?`
- New Container form: `Create Container` now says `Create Group`
- Asset History Records: `Device ID` now says `Record Key`
- Asset History Records: `Device details` now says `Record details`
- Asset History Records: `Device creation` now says `Record creation`
- Asset History Records: `Create new history record` now says `Create new record entry`
- New History Record form: now titled `Create New Record Entry`
- New History Record form: `Record Description` now says `Description`
- New History Record form: `Container Key (optional)` now says `Group Key (optional)`
- New History Record form: `Contained Device Keys (optional, separated with a comma)` now says `Grouped Record Keys (optional, separated with a comma)`
- New History Record form: `Device Image (optional)` now says `Image (optional)`
- New History Record form: `Device tag` now says `Record tag`
- New History Record form: `Create History Record` now says `Create Record Entry`

**Comment by vjaqua** [comment]
What is blocking this PR from merging?
