### ISSUE TITLE
Cleanup Azure resources

### ISSUE THREAD

**Issue by bencoombs** [gosqasorg/asset-provenance-tracking#308]
There are several dev Azure resources. Cleanup the unused resources and create a prod and staging groups.

**Comment by devhawk** [comment]
We had a bunch of test Azure resources that I have cleaned up. At this point we have the following Resource Groups

* rg-gdt-prod - Resource Group for production GOSQAS.org website + backend + BLOB storage
* rg-gdt-test - Resource Group for the redstone dev/test website + backend + BLOB storage
* gdt_archive_rg - Resource Group for a BLOB storage account that's a archive copy of what was in heroku PG
* coco-test-email - Resource Group for @chihlinc 's notification experiments. Will delete when that experiment work is complete
* heprojectdatafunc_group - Resource Group for Helpful Engineering's resource that PubInv is hosting for them
* DefaultResourceGroup-EUS2 - Resource Group that was created by accident during creation of production resource group. I am moving the resources from that group into the `rg-gdt-prod` group and then I will delete this group
