### ISSUE TITLE
[BUG] Footer floats inappropriately....

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#311]
**Describe the bug**
In viewing a long log record, the footer detaches from the bottom of the screen.

**To Reproduce**
Go to the "turtles" URL: https://red-stone-00f5d251e.5.azurestaticapps.net/provenance/8FFYE6suyVbCtVAWe2sP8Y
....which has a long log. I conjecture this bug occurs on any long log record.

**Expected behavior**
The Footer should not "float" upward.

**Screenshots**

![Screenshot 2024-10-10 at 8 43 47 PM](https://github.com/user-attachments/assets/ec55e27e-a30f-47c4-87c6-ba07d84b72d8)

**Desktop (please complete the following information):**
 - MacOS
 - Browser : Chrome

**Comment by RobertLRead** [comment]
@bencoombs you may want to assign this one out. We need to fix it, but I don't think it will stop our data cut over.

**Comment by bencoombs** [comment]
This is fixed in https://github.com/gosqasorg/asset-provenance-tracking/issues/297
