### ISSUE TITLE
Terms and Conditions Footer

### ISSUE THREAD

**Issue by christinacole** [gosqasorg/asset-provenance-tracking#330]
Terms and Conditions document, stylized here 

https://docs.google.com/document/d/1k4IfM-slMRxIEDkCLhRlwZMTMQKWzVtGWo7rL-qfwuc/edit?usp=sharing

**Comment by RobertLRead** [comment]
@melanielaporte , the terms and conditions have been styled by @ninalahoti at figma here:

[https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines](https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines)

This is what we should make.
