### ISSUE TITLE
Update site to match Figma

### ISSUE THREAD

**Issue by vjaqua** [gosqasorg/asset-provenance-tracking#332]
Update gosqas.org to match Figma https://www.figma.com/design/nFA3vMmmL6DdoOIpBmLgIC/Brand-Guidelines?node-id=0-1&node-type=canvas&t=xapC5Rtayo8Fx46Y-0

1. Add Terms & Conditions page
2. Add Homepage
3. Review Figma for additional updates

**Comment by ninalahoti** [comment]
Will add more notes once these edits are complete.

**Comment by RobertLRead** [comment]
@agilpatr is making progress plans to have done by Dec. 5th.

**Comment by agilpatr** [comment]
2. Add Homepage refers to moving the homepage to https://gosqas.org/ and moving the page currently there to https://gosqas.org/gdt
