### ISSUE TITLE
[BUG] Create gosqas-like QR code that links to https://gosqas.org

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#335]
We want this to be a "general" QR that can be used in promotion without compromising anything.

**Comment by ninalahoti** [comment]
I created the QR code and photoshopped it onto the tourniquet photo

![GOSQAS QR Code](https://github.com/user-attachments/assets/655d0b4c-0063-4fe9-aa91-73658f23a7e2)

![tourniquet-new-qr](https://github.com/user-attachments/assets/f2c4941a-7f5b-48e5-88cc-195ce9a2b9db)
