### ISSUE TITLE
Internal Server error attempting to upload photo from my Iphone 6s

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#34]
At about 4:00 pm on Friday the 18th, I tried to upload a photo of a UPS receipt to:
[https://gosqas.org/provenance/5gckf76pbwP77ri4qaSdck](https://gosqas.org/provenance/5gckf76pbwP77ri4qaSdck)

On my phone, it gave me an "internal server error 500". I'm sorry I did not make a screenshot of it. 

When I sent the same image to my Mac computer, and then uploaded them to app under chrome, and it worked.

**Comment by devhawk** [comment]
Can't reproduce
