### ISSUE TITLE
Cant find record?

### ISSUE THREAD

**Issue by bencoombs** [gosqasorg/asset-provenance-tracking#343]
Customer reports they can't find a record on the new site.

**Comment by RobertLRead** [comment]
This URL was not found at the legacy sight nor at the new site: https://provenance-tracking-9c4ad2bbfaee.herokuapp.com/provenance/[WwpmLJzRWFcU4ACDjcGAq1](https://gosqas.org/provenance/WwpmLJzRWFcU4ACDjcGAq1)

Alex created this URL, apparently on the same day that we did the "cutover". We have no explancation for why this does not exist in the Redstone site, and does not exist in Legacy. BTW, the Turtles URL from the legacy database IS in our new database.

This is confusing, but on balance we are going to close this as "won't fix".
