### ISSUE TITLE
Create a Terms of Service Agreement to address potential criminial use of GDT.

### ISSUE THREAD

**Issue by gosqas** [gosqasorg/asset-provenance-tracking#45]
I assume this will require legal input.

Our main concern is the use of the system for encrypted transmission of child pornography or for other illegal activity.

We will cooperate with legal authorities and remove any information if it is identified by key.

**Comment by RobertLRead** [comment]
I have initiated a discussion with Marc Jones on this topic.

**Comment by vjaqua** [comment]
T&C document nearing completion. Avoid website pop-ups that prevent product use. T&C will be it's own page and linked to appropriate product pages.

**Comment by vjaqua** [comment]
A link should be added to the bottom line of the footer. "Please review our terms & conditions." @melanielaporte

**Comment by melanielaporte** [comment]
@vjaqua I need the content to create the link.
