### ISSUE TITLE
[FEATURE REQUEST] Add repo description to repo

### ISSUE THREAD

**Issue by darigovresearch** [gosqasorg/asset-provenance-tracking#58]
Would be helpful to add a description to the repository to help differentiate it from other repositories in your repository list..

Happy to help with this if interested

![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/30328618/ad8b2a3e-21b8-400a-94c0-0168efc6ab4e)

**Comment by RobertLRead** [comment]
I have added a description, thank you for pointing this out.
