### ISSUE TITLE
[FEATURE REQUEST] Add default community guidelines

### ISSUE THREAD

**Issue by darigovresearch** [gosqasorg/asset-provenance-tracking#65]
**Is your feature request related to a problem? Please describe.**
Would be good to have a set of community guidelines which is separate to the contributing guidelines

**Describe the solution you'd like**
There are a few common templates which can be used, usually need a point of contact for raising issues 

**Describe alternatives you've considered**
Create your on but usually the templates are sufficient in most cases

**Additional context**
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by RobertLRead** [comment]
This is done, thanks to @darigovresearch, I wasn't aware templates existed for this. @devhawk I broke our rules and committed it without a PR, but it seemed like a reasonable time save in this case.
