### ISSUE TITLE
[FEATURE REQUEST] Upgrade docs from Wiki

### ISSUE THREAD

**Issue by darigovresearch** [gosqasorg/asset-provenance-tracking#66]
**Is your feature request related to a problem? Please describe.**
Having the docs in a markdown framework for easier consumption and portability of documentation instead of GitHub wikis

**Describe the solution you'd like**
Use any modern framework to generate more usable docs than GitHub wikis as when forking the repo the wiki content does 

**Describe alternatives you've considered**
Just use default markdown in a Docs subfolder can be done until you decide on a given framework

**Additional context**
Can be autogenerated on commit as a nice feature in the future

**Comment by devhawk** [comment]
We don't have much in the way of docs right now, so we will hold off on this until we do

**Comment by paulErdos** [comment]
Relates to #66, #265
