### ISSUE TITLE
[BUG] Hamburger menu not working on small screens

### ISSUE THREAD

**Issue by darigovresearch** [gosqasorg/asset-provenance-tracking#68]
**Describe the bug**
When clicking the menu in the demo in the UI nothing happens

**To Reproduce**
1. Go to https://gosqas.org/
2. Make width of screen small until the menu appears
3. Click menu button
4. Nothing will happen

**Expected behavior**
Dropdown of menus such as home & devices

**Screenshots**
![image](https://github.com/gosqasorg/asset-provenance-tracking/assets/30328618/a665a4ea-28ae-4d2f-8b2e-36d0b2ed0035)

**Comment by darigovresearch** [comment]
The current gosqas site appears to still have it even if it was merged.

What's needed to remove it in the site?

**Comment by devhawk** [comment]
I need to update the site. Will do shortly

**Comment by darigovresearch** [comment]
Can confirm, thanks for the fix, @K42IE & the update in the UI @devhawk
