### ISSUE TITLE
Define a URL as a function the device id as the direct means of entry into the provenance reader.

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#7]
devhawk comment: Can we clarify if this item is referring to the device secret key or the device unique id (which is generated from the device key)? I assume this item means device key since a) the id is generated from the key and b) the key is needed to decrypt the records

**Comment by devhawk** [comment]
the dev branch exposes a `/provenance/:deviceKey` HTTP endpoint which I think fulfills this requirement

**Comment by RobertLRead** [comment]
I meant the device Key.

As an aside, we could tell people what the hash is or offer it as a service, and the programmer could then produce the device ID. The only advantage of this is that a user would never have to give us a key, which we could (if unscrupulous) squirrel away, lowering their security. However, MOST of our users will not have the sophistication to even use the hash; they are nurses and doctors and storekeepers. So I approve of your interpretation; though I can see how a future enhancement might be tighter security, but that is thousands of users away from now.

**Comment by devhawk** [comment]
@RobertLRead currently, I generate the device ID by FNV-64 hashing the hex encoded device key. We *will eventually* hash the key directly, instead of a text encoding, but the FNV library I'm currently using only works on strings. 

Unless I'm missing something, there's no need for users to send us the device ID. They have to send us the device key since we need it to decrypt the records. Since the Device ID is generated from the key, it doesn't need to be sent separately
