### ISSUE TITLE
Begin hosting the site at AWS or Azure or similar.

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#8]
If for some reason Heroku doesn't work, we can choose a different site, but Heroku is preferred due to our familiarity.

**Comment by devhawk** [comment]
SHould we consider CloudFlare? https://www.cloudflare.com/developer-platform/products/

**Comment by RobertLRead** [comment]
After further discussion, we now believe hosting at AWS or Azure maybe better. I have a slight preference for AWS, but it is not important.

**Comment by devhawk** [comment]
Demo deployed to Heroku.
