### ISSUE TITLE
[FEATURE REQUEST] Forbid tags which would make illicit use convenient

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#80]
**Is your feature request related to a problem? Please describe.**

We are concerned about future use by bad actors to communicate illicit material

**Describe the solution you'd like**
We want to make it inconvenient for someone to use GDT to transmit illicit material.  We believe making it impossible to add tags related to explicit sexual acts (using non-medical language). 

**Describe alternatives you've considered**
If it is possible to use a service or an algorithm that flag images as pornographic, we would like to use that also. However, we eventually want to allow in-browser encryption, so in that case we won't be able to do that anyway.

**Additional context**
We may want to create other mechanisms which make our system inconvenient for this purpose.

**Comment by christinacole** [comment]
I edited the list to remove legitimate medical words and the names of countries and regions. Banned Words 1.0: https://docs.google.com/document/d/1qQL-Do1mxfN6TbqNOhXu5fG3Ig71QQlMqUY1hmamfAA/edit?usp=sharing

**Comment by RobertLRead** [comment]
@noramoor2007 Can you put these words in place?  I can't remember if you have the system running---but I will assume you can until you assign it to someone else.

**Comment by devhawk** [comment]
fixed by #218
