### ISSUE TITLE
Allow a set of "tags" or "atoms" to be associated with a provenance record.

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#9]
The intention here is to eventually allow algorithms and a certain amount of data mining and notification of these tags. For example, if there is a "recall" tag, the provenance reader could vividly draw attention to it visually.

The interface for adding new tags can simply be direct addition into a database table (that is, no GUI is needed.) The initial set of tags should be:

- recall
- tested good
- inspected good
- defective
- suspected fraud
- suspected counterfeit
- received
- disposed or consumed
- transmitted to other
- red
- yellow
- green

devhawk comment: Do these need to be encrypted?

**Comment by RobertLRead** [comment]
"Do these need to be encrypted?" --- good question. Yes, I think.

This will make some desirable functions harder, but I think this is what we want for now.

**Comment by devhawk** [comment]
done as part of deployed demo
