### ISSUE TITLE
[FEATURE REQUEST] Adding a form to create a group all at the same time.

### ISSUE THREAD

**Issue by RobertLRead** [gosqasorg/asset-provenance-tracking#96]
We believe that users who want to create containers (that is, batches, lots, boxes, cartons, crates, etc.) will want an aid in doing so, consiting of a form that creates N children and reporting key. I have designed a form to cover this. @judithweng and I have discussed this a big.

![Form for Creating Container Keys (1)](https://github.com/gosqasorg/asset-provenance-tracking/assets/5296671/10b4dbe0-9381-4777-88c0-3a58bf0e08b5)

**Comment by gosqas** [comment]
I think this is done, but it needs to be integrated into the new code @judithweng

**Comment by judithweng** [comment]
This issue has been fixed and integrated into the new code.
